### ISSUE TITLE
Replace safe-focus JS with :focus-visible CSS

### ISSUE THREAD

**Issue by dustin-jw** [sparkbox/sparkpress-wordpress-starter#59]
The purpose of `safe-focus` is to show focus styles when the user is perceived to be doing keyboard things instead of pointer/mouse things, which is the same as what `:focus-visible`, [broadly supported by browsers](https://caniuse.com/?search=focus-visible), is meant for. I'm always going to be in favor of removing JS if CSS can do the same thing, so maybe we can remove the JS and refactor existing focus styles to use `:focus-visible`. To broadly support more browsers, we can combine it with `:not()` to remove focus styles when we don't need them rather than add focus styles when we do.

```css
:focus {
  outline: 0.125rem solid currentcolor;
  outline-style: dashed;
  outline-offset: 0.25rem;
}

:focus:not(:focus-visible) {
  /* making this transparent is better for Windows High Contrast Mode */
  outline-color: transparent;
}
```
